feature/#6-popup guide
imgonnado/sait-web pull request #16
Opened 2023-01-07 14:15 UTC by BonhaengLee

## Description

- 팝업 컴포넌트 작업했습니다. 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/59217352/211155124-3e3fab9f-37cc-460a-a70b-875ad2b68abb.png">

## Commits

- #6 [💄](https://github.com/imgonnado/sait-web/commit/fef46856a605e682ff05dd33ea52887b4aef27b3) [popup](https://github.com/imgonnado/sait-web/commit/fef46856a605e682ff05dd33ea52887b4aef27b3)

## Screenshots
<img width="356" alt="image" src="https://user-images.githubusercontent.com/59217352/211155107-6a3a6e0f-91a3-4eaa-9c36-88aa55ad285f.png">

2023-01-10 12:35 UTC, seambark requested changes

2023-01-10 12:35 UTC, seambark commented on pages/index.tsx
> +      <PopUp
같은 구조를 가진 다른 팝업의 경우 많은 내용이 담겨있어, 차일드 프롭으로 내용을 아예기입하는 방식이 될거 같은데
두개의 팝업의 형식을 통일하는 것은 어떨까요?

2023-01-11 16:27 UTC, BonhaengLee commented on pages/index.tsx
> +      <PopUp
@seambark 변경했습니다. 확인부탁드려요.

2023-01-14 08:33 UTC, seambark approved these changes
확인하였습니다.

2023-01-14 13:21 UTC, merged