feature/#18-setting case
imgonnado/sait-web pull request #19
Opened 2023-01-07 15:34 UTC by BonhaengLee

## Description

- 세팅 페이지 작업했습니다. 상단 Top 컴포넌트(환경 설정)는 임시로 넣었습니다. 추후 작업 완료되면 Top 컴포넌트로 변경합니다.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/59217352/211158462-ae011464-17f7-4ac9-a4ca-fe6891c21364.png">

## Commits

- 253fcc7 #18 :lipstick: setting page

## Screenshots
<img width="335" alt="image" src="https://user-images.githubusercontent.com/59217352/211158470-e42a8fc1-4c79-4781-9df1-12fcfdc4d068.png">

2023-01-08 13:59 UTC, seambark requested changes

2023-01-08 13:59 UTC, seambark commented on pages/setting/index.tsx
> +            <Image
리스트의 화살표 아이콘의 경우 특정한 기능이 없고, 변경사항이 없는 리스트일 경우 백그라운드 이미지로 변경하시는게 좋을거 같습니다. 확인 한번 부탁드립니다.

2023-01-11 16:38 UTC, BonhaengLee commented on pages/setting/index.tsx
> +            <Image
@seambark 커밋 올렸습니다.

2023-01-14 08:35 UTC, seambark approved these changes
확인하였습니다.

2023-01-14 13:22 UTC, merged