feature/#20-points to note
imgonnado/sait-web pull request #21
Opened 2023-01-07 16:14 UTC by BonhaengLee

## Description

- PointsToNote(유의사항) 컴포넌트 작업했습니다.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/59217352/211160147-4698616e-48d4-4c42-b7a3-91ba43ce9841.png">

## Commits

- 0bd6192 #20 :lipstick: Points to Note 마크업, Button에 className 추가

## Screenshots
<img width="313" alt="image" src="https://user-images.githubusercontent.com/59217352/211160138-9ff24484-102b-4a33-a64b-3b140ec85c0e.png">

2023-01-08 14:06 UTC, seambark requested changes

2023-01-08 14:06 UTC, seambark commented on src/components/PointsToNote/PointsToNote.tsx
> +            <Text
리스트 스타일의 텍스트는 컴포넌트로 분리하지 않고 리스트 자체의 스타일은 주시면 좋을 것 같습니다.

2023-01-11 16:43 UTC, BonhaengLee commented on src/components/PointsToNote/PointsToNote.tsx
> +            <Text
@seambark 변경해서 올렸습니다.

2023-01-14 08:27 UTC, seambark approved these changes
확인하였습니다!

2023-01-14 13:25 UTC, merged